@categoryId = 3240fd12-3bcd-4f83-e7c5-08da5678c9cc

### Get All Categories
GET {{host}}/api/categories

### Get Category by Id
GET {{host}}/api/categories/{{categoryId}}

### Create Category
POST {{host}}/api/categories
Content-Type: application/json

{
    "Name": "Phones",
    "Image": null,
    "ParentCategory": null
}

### Update Category
PUT {{host}}/api/categories/{{categoryId}}
Content-Type: application/json

{
    "id": "{{categoryId}}",
    "Name": "TV updated",
    "Image": null,
    "ParentCategory": "27172db9-5d6c-4b75-e7c4-08da5678c9cc"
}

### Delete Category
DELETE  {{host}}/api/categories/{{categoryId}}