@categoryId = 27172db9-5d6c-4b75-e7c4-08da5678c9cc
@itemId = 57e96b41-435d-471d-d311-08da5678c9de

### Get All Items
GET {{host}}/api/items?
#pageSize=2
#&pageIndex=1 HTTP/2.0

### Get Item by Id
GET {{host}}/api/items/{{itemId}}

### Create Item
POST {{host}}/api/items
Content-Type: application/json

{
    "categoryId": "{{categoryId}}",
    "name": "Third item",
    "price": 12.5000,
    "amount": 10,
    "description": "Samsung 11N",
    "image": null
}

### Update Item
PUT {{host}}/api/items/{{itemId}}
Content-Type: application/json

{
  "id": "{{itemId}}",
  "categoryId": "{{categoryId}}",
  "name": "Samsung updated via message bus 4",
  "price": 15,
  "amount": 10,
  "description": "Samsung TV",
  "image": "imageurl"
}

### Delete Item
DELETE  {{host}}/api/items/{{itemId}}